manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dzervas
      url-base: https://github.com/dzervas
    - name: runtimeco
      url-base: https://github.com/runtimeco
  projects:
    - name: zmk
      # remote: zmkfirmware
      remote: dzervas
      revision: main
      import: app/west.yml
    - name: mcuboot
      remote: runtimeco
      revision: main
  self:
    path: config
